
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module encoding #(parameter N = 23)(

	//////////// CLOCK //////////
	input 		          		CLOCK_50,

	//////////// LED //////////
	output		     		LED0,


	//////////// SW //////////
	input 		     		SW0
);

    wire clk;
    wire nrst;
    wire out0;
    assign clk = CLOCK_50;
	 assign nrst = SW0;
	 assign LED0 = out0;
	 
    reg [(N*N)-1:0] seeds;
    wire [(N*N)-1:0] cells;
    assign out0 = cells[0];
        
    GameOfLife #(.N(N)) itsmylife(
        .clk(clk),
        .nrst(nrst),
        .seeds(seeds),
        .cells(cells)
    );    
    
    always @ (posedge clk)
    if (nrst == 0)
        seeds <= 64'b01000000_00100000_11100000_00000000_00000000_00000000_00000000_00000000;
		
endmodule


